<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.github.amu10</groupId>
    <artifactId>easy-at-parent</artifactId>
    <version>0.1.2</version>
  </parent>
  <name>easy-at-spring-boot3-starter</name>
  <description>Spring Boot 3.x auto-configuration starter for easy-at.</description>
  <url>https://github.com/amu10/easyat</url>
  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <scm>
    <connection>scm:git:https://github.com/amu10/easyat.git</connection>
    <developerConnection>scm:git:ssh://git@github.com/amu10/easyat.git</developerConnection>
    <url>https://github.com/amu10/easyat</url>
    <tag>v0.1.2</tag>
  </scm>
  <developers>
    <developer>
      <id>amu10</id>
      <name>amu10</name>
      <url>https://github.com/amu10</url>
    </developer>
  </developers>
  <artifactId>easy-at-spring-boot3-starter</artifactId>
  <properties>
    <maven.compiler.release>17</maven.compiler.release>
    <boot.version>3.3.3</boot.version>
  </properties>
  <dependencies>
    <dependency>
    <groupId>io.github.amu10</groupId>
      <artifactId>easy-at-spring</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
    <groupId>io.github.amu10</groupId>
      <artifactId>easy-at-storage-file</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
    <groupId>io.github.amu10</groupId>
      <artifactId>easy-at-storage-redis</artifactId>
      <version>${project.version}</version>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>redis.clients</groupId>
      <artifactId>jedis</artifactId>
      <version>4.4.6</version>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-aop</artifactId>
      <version>${boot.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-jdbc</artifactId>
      <version>${boot.version}</version>
    </dependency>
    <dependency>
      <groupId>jakarta.servlet</groupId>
      <artifactId>jakarta.servlet-api</artifactId>
      <version>6.0.0</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <version>${boot.version}</version>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
