package io.github.easyat.jdbc;

import io.github.easyat.core.*;
import javax.sql.DataSource;
import java.io.*;
import java.sql.*;
import java.util.*;

/** JDBC-backed source of truth for global transactions and undo records. */
public final class JdbcAtRepository implements ConnectionBoundAtRepository {
    private final DataSource dataSource;
    public JdbcAtRepository(DataSource dataSource){this.dataSource=dataSource;}
    @Override public void create(AtTransaction tx){
        String sql="INSERT INTO easy_at_global(xid,name,status,timeout_at,retry_count,next_retry_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)";
        try(Connection c=dataSource.getConnection();PreparedStatement p=c.prepareStatement(sql)){long now=System.currentTimeMillis();p.setString(1,tx.getXid());p.setString(2,tx.getName());p.setString(3,tx.getStatus().name());p.setTimestamp(4,new Timestamp(tx.getDeadline()));p.setInt(5,tx.getRetries());p.setTimestamp(6,timestamp(tx.getNextRetryAt()));p.setTimestamp(7,new Timestamp(now));p.setTimestamp(8,new Timestamp(now));p.executeUpdate();}catch(SQLException e){throw new AtException("Cannot create AT transaction",e);}
    }
    @Override public Optional<AtTransaction> find(String xid){
        String sql="SELECT xid,name,status,timeout_at,retry_count,next_retry_at,created_at FROM easy_at_global WHERE xid=?";
        try(Connection c=dataSource.getConnection();PreparedStatement p=c.prepareStatement(sql)){p.setString(1,xid);try(ResultSet r=p.executeQuery()){if(!r.next())return Optional.empty();AtTransaction tx=new AtTransaction(r.getString(1),r.getString(2),r.getTimestamp(7).getTime(),r.getTimestamp(4).getTime());Timestamp next=r.getTimestamp(6);tx.restore(AtStatus.valueOf(r.getString(3)),r.getInt(5),next==null?0:next.getTime());loadUndo(c,tx);return Optional.of(tx);}}catch(SQLException e){throw new AtException("Cannot read AT transaction",e);}
    }
    @Override public void save(AtTransaction tx){
        try(Connection c=dataSource.getConnection()){boolean auto=c.getAutoCommit();try{c.setAutoCommit(false);String update="UPDATE easy_at_global SET status=?,retry_count=?,next_retry_at=?,updated_at=? WHERE xid=?";try(PreparedStatement p=c.prepareStatement(update)){p.setString(1,tx.getStatus().name());p.setInt(2,tx.getRetries());p.setTimestamp(3,timestamp(tx.getNextRetryAt()));p.setTimestamp(4,new Timestamp(System.currentTimeMillis()));p.setString(5,tx.getXid());if(p.executeUpdate()!=1)throw new AtException("Transaction not found: "+tx.getXid());}try(PreparedStatement d=c.prepareStatement("DELETE FROM easy_at_undo_log WHERE xid=?")){d.setString(1,tx.getXid());d.executeUpdate();}for(UndoRecord undo:tx.getUndoRecords())insertUndo(c,undo);c.commit();}catch(Exception e){c.rollback();if(e instanceof AtException)throw (AtException)e;throw new AtException("Cannot save AT transaction",e);}finally{c.setAutoCommit(auto);}}catch(SQLException e){throw new AtException("Cannot save AT transaction",e);}
    }
    @Override public List<AtTransaction> recoverable(long now,int limit){
        String sql="SELECT xid FROM easy_at_global WHERE (status='ACTIVE' AND timeout_at<=?) OR (status='ROLLBACK_FAILED' AND (next_retry_at IS NULL OR next_retry_at<=?)) ORDER BY updated_at ASC";List<AtTransaction> result=new ArrayList<AtTransaction>();try(Connection c=dataSource.getConnection();PreparedStatement p=c.prepareStatement(sql)){p.setTimestamp(1,new Timestamp(now));p.setTimestamp(2,new Timestamp(now));try(ResultSet r=p.executeQuery()){while(r.next()&&result.size()<limit){Optional<AtTransaction> tx=find(r.getString(1));if(tx.isPresent())result.add(tx.get());}}return result;}catch(SQLException e){throw new AtException("Cannot scan recoverable transactions",e);}
    }
    /** Writes with the caller-owned connection; this is the local-transaction atomicity path. */
    @Override public void append(Connection connection,UndoRecord record){try{insertUndo(connection,record);}catch(SQLException e){throw new AtException("Cannot append connection-bound undo record",e);}}
    @Override public void updateUndo(Connection connection,String xid,String undoId,RowImage after){String sql="UPDATE easy_at_undo_log SET after_image=?,updated_at=? WHERE xid=? AND undo_id=?";try(PreparedStatement p=connection.prepareStatement(sql)){p.setBytes(1,serialize(after));p.setTimestamp(2,new Timestamp(System.currentTimeMillis()));p.setString(3,xid);p.setString(4,undoId);if(p.executeUpdate()!=1)throw new AtException("Undo record not found: "+undoId);}catch(SQLException e){throw new AtException("Cannot update connection-bound undo record",e);}}
    @Override public void removeUndo(Connection connection,String xid,String undoId){try(PreparedStatement p=connection.prepareStatement("DELETE FROM easy_at_undo_log WHERE xid=? AND undo_id=?")){p.setString(1,xid);p.setString(2,undoId);p.executeUpdate();}catch(SQLException e){throw new AtException("Cannot discard connection-bound undo record",e);}}
    private void loadUndo(Connection c,AtTransaction tx)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT undo_id,resource_id,table_name,pk_name,pk_value,rollback_sql,rollback_params,before_image,after_image,status FROM easy_at_undo_log WHERE xid=? ORDER BY created_at")){p.setString(1,tx.getXid());try(ResultSet r=p.executeQuery()){while(r.next()){UndoRecord u=new UndoRecord(r.getString(1),tx.getXid(),r.getString(2),r.getString(3),r.getString(4),deserialize(r.getBytes(5)),r.getString(6),(Object[])deserialize(r.getBytes(7)));u.setBeforeImage((RowImage)deserialize(r.getBytes(8)));u.setAfterImage((RowImage)deserialize(r.getBytes(9)));if("ROLLED_BACK".equals(r.getString(10)))u.markRolledBack();tx.addUndo(u);}}}}
    private void insertUndo(Connection c,UndoRecord u)throws SQLException{String sql="INSERT INTO easy_at_undo_log(undo_id,xid,resource_id,table_name,pk_name,pk_value,rollback_sql,rollback_params,before_image,after_image,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)";try(PreparedStatement p=c.prepareStatement(sql)){long now=System.currentTimeMillis();p.setString(1,u.getId());p.setString(2,u.getXid());p.setString(3,u.getResourceId());p.setString(4,u.getTableName());p.setString(5,u.getPrimaryKeyColumn());p.setBytes(6,serialize(u.getPrimaryKeyValue()));p.setString(7,u.getRollbackSql());p.setBytes(8,serialize(u.getParameters()));p.setBytes(9,serialize(u.getBeforeImage()));p.setBytes(10,serialize(u.getAfterImage()));p.setString(11,u.isRolledBack()?"ROLLED_BACK":"EXECUTED");p.setTimestamp(12,new Timestamp(now));p.setTimestamp(13,new Timestamp(now));p.executeUpdate();}}
    private static Timestamp timestamp(long value){return value<=0?null:new Timestamp(value);} private static byte[] serialize(Object value){if(value==null)return null;try{ByteArrayOutputStream b=new ByteArrayOutputStream();new ObjectOutputStream(b).writeObject(value);return b.toByteArray();}catch(IOException e){throw new AtException("Cannot serialize AT value",e);}} private static Object deserialize(byte[] value){if(value==null)return null;try{return new ObjectInputStream(new ByteArrayInputStream(value)).readObject();}catch(Exception e){throw new AtException("Cannot deserialize AT value",e);}}
}
