<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.github.amu10</groupId>
    <artifactId>easy-at-parent</artifactId>
    <version>0.1.1</version>
  </parent>
  <name>easy-at-jdbc</name>
  <description>JDBC undo log executor, global lock manager and SQL image generator for easy-at.</description>
  <url>https://github.com/amu10/easyat</url>
  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <scm>
    <connection>scm:git:https://github.com/amu10/easyat.git</connection>
    <developerConnection>scm:git:ssh://git@github.com/amu10/easyat.git</developerConnection>
    <url>https://github.com/amu10/easyat</url>
    <tag>v0.1.1</tag>
  </scm>
  <developers>
    <developer>
      <id>amu10</id>
      <name>amu10</name>
      <url>https://github.com/amu10</url>
    </developer>
  </developers>
  <artifactId>easy-at-jdbc</artifactId>
  <dependencies>
    <dependency>
    <groupId>io.github.amu10</groupId>
      <artifactId>easy-at-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.github.jsqlparser</groupId>
      <artifactId>jsqlparser</artifactId>
      <version>4.9</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.17.2</version>
    </dependency>
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <version>2.2.224</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
